config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  resources :comments, only: [:create]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
 get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'contacts', to: 'pages#contacts'

  get 'about', to: 'pages#about'
  get 'pages/home'
  get 'twit-news', to: 'pages#twitter'
  get 'pages/about'

  get 'pages/contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to:  "pages#home"
mount ActionCable.server => '/cable'

end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id
  belongs_to :topic

  has_many :comments, dependent: :destroy
  scope :recent, -> { order(created_at: :desc)}
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

    before_action :set_side_bar_topics, except: [:update, :create, :destroy, :toggle_status]

  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout 'blog'

  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(5)

    else
      @blogs = Blog.published.page(params[:page]).per(5)

    end
  @page_title= "My crusade's Blog | We will take Jerusalem!"

  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog =Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      @seo_keywords = " DEUS VULT AVE MARIA NON NOBIS DOMINE"
      @page_title = @blog.title
    else
      redirect_to blogs_path, notice: 'You are not authorized tp access this page'
    end

  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.jsont
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end
  def toggle_status
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
      end
    redirect_to blogs_url, notice: "#{@blog.title}'s status has been updated"
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end


end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, lang)
      CodeRay.scan(code, lang).div

    end
  end

def markdown(text)
  coderayified = CodeRayify.new(filter_html: true,hard_wrap: true)

  options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      lax_html_blocks: true,
      autolink: true,

  }

  markdown_to_html = Redcarpet::Markdown.new( coderayified, options)
  markdown_to_html.render(text).html_safe

end

  def blog_status_color item
    if item.draft?
      'color: red;'
    else
      'color: blue;'
    end
  end


end

app/views/blogs/_admin_actions.html.haml
- if logged_in?(:site_admin)
  %nav.breadcrumb.blogcrumb

    = link_to fa_icon('file-text'), toggle_status_blog_path(blog), style: blog_status_color(blog)

    = link_to fa_icon('pencil-square-o'), edit_blog_path(blog)
    = link_to fa_icon('trash'), blog, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/blogs/_blog.html.haml
.blog-post
  %h2.blog-post-title= link_to blog.title.upcase, blog
  %p.blog-post-meta
    = succeed " ago " do
      = distance_of_time_in_words_to_now(blog.created_at)
  = render 'blogs/admin_actions', blog: blog

  %p= blog.body

app/views/blogs/_blog_ruler.html.haml
%hr

app/views/blogs/_form.html.haml
= form_for blog do |f|
  - if blog.errors.any?
    - blog.errors.full_messages.each do |error|
      = alert_generator error

  .form-group
    = f.text_field :title, class: 'form-control', placeholder: "Title"

  .form-group
  = f.label :topic_id
  = f.collection_select(:topic_id, Topic.all, :id, :title, |
                        {                                  |
                            selected: blog.topic_id,       |
                            include_blank: true            |
                        },                                 |
                        class: 'form-control')             |

  .form-group
    = f.radio_button :status, 'draft'
    = f.label :status, 'Draft'
    = f.radio_button :status, 'published'
    = f.label :status, 'Published'

  .form-group
    = f.text_area :body, class: 'form-control', rows: 15, placeholder: "Body"
  .form-group
    = f.submit 'Save', class: 'btn btn-primary '

-#= form_tag(blogs_path) do
-#  .form-group
-#    = label_tag 'blog[title]', 'Blog Title'
-#    = text_field_tag 'blog[title]', blog.title, class: 'form-control'
-#  .form-group
-#    = label_tag 'blog[body]', 'Blog Bodye'
-#    = text_area_tag 'blog[body]', blog.body, class: 'form-control', rows: 15
-#
-#  .form-group
-#    = submit_tag 'Save', class: 'btn btn-primary'

app/views/blogs/edit.html.haml
.col-sm-8.blog-main
  %h1 Editing blog

  = render 'form', blog: @blog

  = link_to 'Show', @blog

  = link_to 'Back', blogs_path

app/views/blogs/index.html.haml
.col-sm-8.blog-main
  = paginate @blogs
  = render @blogs

  = paginate @blogs

app/views/blogs/new.html.haml
.col-sm-8.blog-main
  %h1 New blog

  = render 'form', blog: @blog

  = link_to 'Back', blogs_path

app/views/blogs/show.html.haml
.col-sm-8.blog-main
  - if logged_in?(:site_admin)
    = link_to 'Edit', edit_blog_path(@blog)
  %h2= @blog.title

  %nav.breadcrumb
    = link_to "Home", root_path, class: 'breadcrumb-item'
    = link_to @blog.topic.title, @blog.topic, class: 'breadcrumb-item'
    %span.breadcrumb-item.active= @blog.title.downcase.capitalize
    - if logged_in?(:site_admin)
      %span.pull-right
        = link_to fa_icon('pencil-square-o'), edit_blog_path(@blog)
        = link_to fa_icon('trash'), @blog ,method: :delete, data: { confirm: 'Are you sure?' }



  %p= @blog.topic.title
  .blog-body
    %p= markdown @blog.body

  = render 'comments/comment_form'

  #comments{ "data-blog-id" => "#{@blog.id}"}
    = render @blog.comments

app/views/blogs/topicform.html.haml
.form-group
  = f.label :topic_id
  = f.collection_select(:topic_id, Topic.all, :id, :title, |
                        {                                  |
                            selected: blog.topic.id,       |
                            include_blank: true            |
                        },                                 |
                        class: 'form-control'              |
    )                                                      |