config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  resources :comments, only: [:create]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
 get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'contacts', to: 'pages#contacts'

  get 'about', to: 'pages#about'
  get 'pages/home'
  get 'twit-news', to: 'pages#twitter'
  get 'pages/about'

  get 'pages/contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to:  "pages#home"
mount ActionCable.server => '/cable'

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda  {|attr| attr["name"].blank? }
  validates_presence_of :title, :body
 scope :by_position, -> { order(position: :asc)}

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

def  self.deus_vult
  where(subtitle:  'DEUS VULT')
end

  scope :ave_maria, -> { where(subtitle: "AVE MARIA")}



end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'

  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :sort ,:edit]}, site_admin: :all
  def index
    @portfolios = Portfolio.by_position

  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end
  def new
    @portfolio = Portfolio.new


  end
  def show

  end

  def edit

  end

  def update
     @portfolio.update_attributes(portfolio_params)
      if @portfolio.save
        redirect_to portfolio_show_path(@portfolio), notice: "This portfolio was Successcully updated"
      else
        render 'edit'
      end
  end
  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      redirect_to portfolio_show_path(@portfolio), notice: "Portfolio has been created"
    else
      render 'new'
    end
  end

  def destroy
    if @portfolio.destroy
      redirect_to portfolios_path, alert: 'Portfolio was successfully deleted'
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image,
                                      technologies_attributes: [:id,:name, :_destroy])
  end

  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def is_sortable?
    if logged_in?(:site_admin)
      "row sortable"
    else
      "row"
    end
  end


  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end


  end

app/views/portfolios/_form.html.haml
= form_for portfolio do |f|
  - if portfolio.errors.any?
    - portfolio.errors.full_messages.each do |error|
      = alert_generator error



  .row
    .col-md-6

      .form-group
        =f.label :title
        =f.text_field :title, class: 'form-control'

      .form-group
        =f.label :subtitle
        =f.text_field :subtitle, class: 'form-control'

        .form-group
          %label.btn.btn-primary{ style: "margin-top: 20px;"}
            Upload main image
            =f.file_field :main_image, class: 'form-control', style: 'display: none;'

        .form-group
          %label.btn.btn-primary
            Upload thumb image
            =f.file_field :thumb_image, class: 'form-control', style: 'display: none;'
    .col-md-6

      .form-group
        =f.label :body
        =f.text_area :body, class: 'form-control', rows: 16

    .col-md-12

  %hr

  %h2 Technologies used
  %div
    =f.fields_for :technologies do |tech_form|
      = render 'technology_fields', f: tech_form
  %div
    = link_to_add_association 'Add technology', f, :technologies


  %hr

  = f.submit "Save portoflio", class: 'btn btn-md btn-success btn-block'

app/views/portfolios/_portfolio.html.haml
.col-md-4
  .card{ "data-id" => "#{portfolio.id}" }
    = image_tag  portfolio_img(portfolio.thumb_image, 'thumb'), width: '100%'
    %p.card-text
      %span= link_to portfolio.title, portfolio_show_path(portfolio)
      %span= portfolio.subtitle

app/views/portfolios/_technology_fields.html.haml
.form-group.nested-fields
  = f.label :name
  = f.text_field :name, class: 'form-control'
  = link_to_remove_association 'Remove technology', f

app/views/portfolios/edit.html.haml
.container.portfolio-container
  %h1 Update your portfolio

  = render 'form', portfolio: @portfolio

app/views/portfolios/index.html.haml
.album.text-muted
  .container
    = sample_helper('alert alert-warning')
    %div{:class => "#{is_sortable?}"}
      = render @portfolios

app/views/portfolios/new.html.haml
.container.portfolio-container
  %h1 NEW Portfolio
  = render 'form',portfolio: @portfolio

app/views/portfolios/show.html.haml
.container
  .row
    .col-md-7.portfolio-container.img-circle
      = image_tag portfolio_img(@portfolio.main_image, 'main'), width: '100%'
    .col-md-5
      %h1= @portfolio.title
      %hr
      %em= @portfolio.subtitle

      %p= @portfolio.body
      %hr
      %h3 Technologies Used:
      - @portfolio.technologies.each do |t|
        %p.text-capitalize.text-nowrap= t.name

      - if  logged_in?(:site_admin)
        .row
          = link_to "Edit Item", edit_portfolio_path(@portfolio), class: 'btn btn-warning'