config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  resources :comments, only: [:create]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
 get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'contacts', to: 'pages#contacts'

  get 'about', to: 'pages#about'
  get 'pages/home'
  get 'twit-news', to: 'pages#twitter'
  get 'pages/about'

  get 'pages/contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to:  "pages#home"
mount ActionCable.server => '/cable'

end

app/views/shared/_application_footer.html.haml
.mastfoot
  .inner
    %p.app-footer= copyright_generator

app/views/shared/_application_nav.html.haml
.masthead.clearfix
  .inner
    .h3.masthead-brand Gravity Slave
    %nav.nav.nav-masthead.app-nav
      = nav_helper('nav-link', 'span')
      = login_helper('nav-link')

app/views/shared/_blog_ftr.html.haml
%footer.blog-footer
  %p
    Blog template built for
    = link_to 'Bootstrap',  "https://getbootstrap.com"
    by
    = succeed '*' do

      = link_to '@mdo', "https://twitter.com/mdo"
  %p
    = link_to 'Back to top', '#'


  = sample_helper('blog')

app/views/shared/_blog_msthd.html.haml
.blog-header
  .container
    %h1.blog-title The Bootstrap Blog
    %p.lead.blog-description An exmple of blog
    = link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin)

app/views/shared/_blog_nav.html.haml
%nav.navbar.navbar-toggleable-md.navbar-light.bg-faded.blog-nav
  %button.navbar-toggler.navbar-toggler-right{type: "button", "data-toggle" => "collapse", "data-target" => "#navbarSupportedContent",
  "aria-controls" => 'navbarSupportedContent', "aria-expanded" => 'false', "aria-label" => "Toggle navigation"}

    %span.navbar-toggler-icon

  .container
    = link_to 'Gravity Slave',root_path, class: 'navbar-brand '

    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        = nav_helper('nav-link', 'li')
        = login_helper 'nav-link'

app/views/shared/_blog_sidebar.html.haml
.col-sm-3.offset-sm-1.blog-sidebar
  .sidebar-module.sidebar-module-inset
    %h4 About
    %p
      Etiam porta
      %em sem malesuada magna
      mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.


  = sample_helper('alert alert-info blog-sidebar-source')

  .sidebar-module
    %h4 Topics
    - @side_bar_topics.each do |topic|
      %p= link_to topic.title, topic

  .sidebar-module
    %h4 Elsewhere
    %ol.list-unstyled.social-links
      %li= link_to fa_icon("github"), "https://github.com"
      %li= link_to fa_icon("facebook"), "https://facebook.com"
      %li= link_to fa_icon("twitter"), "https://twitter.com"
      %li= link_to fa_icon("bitbucket"), 'http://bitbucket.com'
      %li= link_to fa_icon("vk"), 'https://vk.com'
      %li= link_to fa_icon("instagram"), 'https://instagram.com'
      %li= link_to fa_icon("reddit"), 'https://reddit.com'

app/views/shared/_nav.html.haml
%div{ class: "#{location}"}
  = link_to "Home", root_path, class: 'btn btn-sm btn-primary'
  = link_to "About", about_path, class: 'btn btn-sm btn-primary'
  = link_to "Contact", contacts_path, class: 'btn btn-sm btn-primary'
  = link_to "Blog", blogs_path, class: 'btn btn-sm btn-primary'
  = link_to "Portfolio", portfolios_path, class: 'btn btn-sm btn-primary'

app/views/shared/_portfolio_footer.html.haml
%footer.text-muted
  .container
    %p.float-right
      = succeed " / " do

        = link_to 'Back to top', '#'
      = succeed " / " do
        = link_to "View all portfolios", portfolios_path
      = link_to "Create new portfolio", new_portfolio_path  if logged_in?(:site_admin)
    %p= copyright_generator

    %p= sample_helper('portfolio')

app/views/shared/_portfolio_masthead.html.haml
%section.jumbotron.text-center
  .container
    %h1.jumbotron-heading 9GAG Ipsum
    %p.lead.text-muted
      Dolor mixtape letterpress, freegan chillwave fixie marfa selfies vaporware pop-up lo-fi leggings. fixie marfa selfies vaporware pop-up lo-fi leggings. Readymade +1 sartorial bushwick enim man bun vaporware succulents four dollar toast, labore blue bottle hashtag. Normcore culpa fanny pack, flannel dreamcatcher tilde enim yr crucifix accusamus jean shorts eiusmod cronut narwhal. Nesciunt elit direct trade exercitation, 3 wolf moon gentrify waistcoat eiusmod brunch cillum distillery affogato seitan
      .clearfix
      = link_to 'About Me', about_path,method: :get, class: 'btn btn-primary'
      = link_to 'Blogs', blogs_path, method: :get, class: 'btn btn-secondary'

app/views/shared/_portfolio_nav.html.haml
#navbarHeader.collapse.bg-inverse
  .container
    .row
      .col-sm-8.py-4
        %h4.text-white Gag Ipsum
        %p.text-muted Forage godard retro succulents bespoke, do messenger bag mustache. Vaporware retro yuccie, minim blog next level kitsch forage magna viral fashion axe nesciunt letterpress. Elit vice celiac, selvage nihil pour-over fap helvetica messenger bag lo-fi pabst cold-pressed vexillologist.
      .col-sm-4.py-4
        %h4.text-white Contact
        %ul.list-unstyled
          = nav_helper('text-white', 'li')
          = login_helper('text-white')

.navbar.navbar-inverse.bg-inverse
  .container.d-flex.justify-content-between
    %a.navbar-brand{:href => "#"} DEUS VULT
    %button.navbar-toggler{"aria-controls" => "navbarHeader", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarHeader", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon